import { StyleSheet } from '@react-pdf/renderer';

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: 'NotoSansSC',
    fontSize: 10,
    paddingTop: 36,
    paddingBottom: 44,
    paddingHorizontal: 40,
    color: '#1e293b',
    lineHeight: 1.5,
  },
  coverTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: '#0f172a',
    marginBottom: 6,
  },
  coverMeta: {
    fontSize: 10,
    color: '#64748b',
    marginBottom: 4,
  },
  section: {
    marginTop: 18,
    marginBottom: 8,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  sectionBar: {
    width: 3,
    height: 18,
    backgroundColor: '#7c3aed',
    marginRight: 8,
    borderRadius: 2,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: '#0f172a',
  },
  sectionDesc: {
    fontSize: 9,
    color: '#64748b',
    marginBottom: 8,
  },
  card: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 6,
    padding: 10,
    marginBottom: 8,
    backgroundColor: '#f8fafc',
  },
  summaryBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#7c3aed',
    color: '#ffffff',
    fontSize: 8,
    fontWeight: 700,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 10,
    marginBottom: 6,
  },
  summaryText: {
    fontSize: 10,
    color: '#334155',
    marginBottom: 4,
  },
  summaryFoot: {
    fontSize: 8,
    color: '#94a3b8',
    marginTop: 4,
  },
  table: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginTop: 6,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  tableHeader: {
    backgroundColor: '#f1f5f9',
  },
  tableCell: {
    flex: 1,
    paddingVertical: 5,
    paddingHorizontal: 4,
    fontSize: 8,
  },
  tableCellWide: {
    flex: 1.4,
    paddingVertical: 5,
    paddingHorizontal: 4,
    fontSize: 8,
  },
  tableCellNarrow: {
    flex: 0.7,
    paddingVertical: 5,
    paddingHorizontal: 4,
    fontSize: 8,
  },
  pkRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  pkBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
    backgroundColor: '#f8fafc',
  },
  pkMid: {
    width: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pkName: {
    fontSize: 11,
    fontWeight: 700,
    marginBottom: 4,
  },
  pkScore: {
    fontSize: 18,
    fontWeight: 700,
    color: '#6d28d9',
  },
  pkScoreRival: {
    fontSize: 18,
    fontWeight: 700,
    color: '#a21caf',
  },
  pkBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    fontSize: 7,
    color: '#a21caf',
    backgroundColor: '#fae8ff',
    paddingVertical: 2,
    paddingHorizontal: 5,
    borderRadius: 8,
  },
  compareRow: {
    marginBottom: 8,
  },
  compareBarTrack: {
    height: 6,
    backgroundColor: '#e2e8f0',
    borderRadius: 3,
    marginVertical: 4,
    flexDirection: 'row',
  },
  compareBarFill: {
    height: 6,
    backgroundColor: '#7c3aed',
    borderRadius: 3,
  },
  compareLabel: {
    fontSize: 8,
    color: '#64748b',
    textAlign: 'center',
  },
  compareValues: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 9,
    fontWeight: 700,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
  },
  metricCard: {
    width: '31%',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 6,
    padding: 8,
    backgroundColor: '#f8fafc',
  },
  metricTitle: {
    fontSize: 8,
    color: '#64748b',
    marginBottom: 2,
  },
  metricValue: {
    fontSize: 14,
    fontWeight: 700,
    color: '#0f172a',
  },
  tagWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
  },
  tag: {
    fontSize: 9,
    color: '#6d28d9',
    backgroundColor: '#ede9fe',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 10,
  },
  optCard: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  optTitle: {
    fontSize: 11,
    fontWeight: 700,
    marginBottom: 6,
  },
  optLine: {
    fontSize: 9,
    color: '#475569',
    marginBottom: 3,
  },
  muted: {
    color: '#64748b',
  },
  selfHighlight: {
    backgroundColor: '#f5f3ff',
  },
  ellipsisRow: {
    textAlign: 'center',
    color: '#94a3b8',
    fontSize: 8,
    paddingVertical: 4,
  },
});
